name: package_info_plus_riverpod
description: "Riverpod Provider for package_info_plus"
version: 1.1.0
repository: https://github.com/eaglesakura/package_info_plus_riverpod/

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^3.0.0
  flutter_riverpod: ^3.0.0
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
